stages:
  - build
  - test
  - push

variables:
  IMAGE_TAR_PATH: image.tar

docker:build:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context .
      --dockerfile ./Dockerfile
      --destination "$CI_REGISTRY_IMAGE"
      --no-push
      --cache=true
      --cache-repo="$CI_REGISTRY_IMAGE/cache"
      --tarPath "$IMAGE_TAR_PATH"
  artifacts:
    paths:
      - $IMAGE_TAR_PATH
    when: on_success

docker:test:
  stage: test
  image: 
    name: gcr.io/gcp-runtimes/container-structure-test:debug
    entrypoint: [""]
  script:
    - /container-structure-test test
      --driver tar
      --image "$IMAGE_TAR_PATH"
      --config ./tests/config.yaml

docker:latest:push:
  stage: push
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane push $IMAGE_TAR_PATH $CI_REGISTRY_IMAGE:latest
  only:
    - tags

docker:tag:push:
  stage: push
  image:
    name: gcr.io/go-containerregistry/crane:debug
    entrypoint: [""]
  script:
    - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - crane push $IMAGE_TAR_PATH $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  only:
    - tags